---
title: "Ihre Honig Rechnung"
author: "Imkerei Holz"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
params:
  n: NA
---

```{r setup, include=FALSE}
# A Prefix nulling hook.

# Make sure to keep the default for normal processing.
default_output_hook <- knitr::knit_hooks$get("output")

# Output hooks handle normal R console output.
knitr::knit_hooks$set( output = function(x, options) {

  comment <- knitr::opts_current$get("comment")
  if( is.na(comment) ) comment <- ""
  can_null <- grepl( paste0( comment, "\\s*\\[\\d?\\]" ),
                     x, perl = TRUE)
  do_null <- isTRUE( knitr::opts_current$get("null_prefix") )
  if( can_null && do_null ) {
    # By default R print output aligns at the right brace.
    align_index <- regexpr( "\\]", x )[1] - 1
    # Two cases: start or newline
    re <- paste0( "^.{", align_index, "}\\]")
    rep <- comment
    x <- gsub( re, rep,  x )
    re <- paste0( "\\\n.{", align_index, "}\\]")
    rep <- paste0( "\n", comment )
    x <- gsub( re, rep,  x )
  }

  default_output_hook( x, options )

})

knitr::opts_template$set("kill_prefix"=list(comment=NA, null_prefix=TRUE))
```

```{r, include=FALSE}
# The `params` object is available in the document.
library(knitr)
temp_rech <- params$n

```

```{r salud, echo=FALSE, message=FALSE, warning=FALSE, comment=NA, null_prefix=TRUE}
noquote(c("Liebe/r", as.character(temp_rech[1,2])))
```
Dies ist die Rechung ihrer letztn Honigbestellung bei unserer Imkerei. Bitte überweisen sie den Betrag  auf folgendes Konto: IBAN: DE15 12030000 10.

```{r zusammenfassung33, echo=FALSE, message=FALSE, warning=FALSE, null_prefix=TRUE}

kable(temp_rech, caption = paste0("RN:", temp_rech[1,8]))

```

Das macht eine gesamt Summe von:
```{r zusammenfassung3, echo=FALSE, message=FALSE, warning=FALSE, comment=NA, null_prefix=TRUE}
noquote(paste0(sum(as.numeric(temp_rech[,7])), "Euro"))
```